#+title: clumped-processing
[[https://zenodo.org/badge/latestdoi/400205023][https://zenodo.org/badge/400205023.svg]]

This is processing code for the clumped isotope measurements made with the Thermo Fisher MAT 253 plus isotope ratio mass spectrometer with the Kiel IV automatic line, located in the Vening-Meineszbuilding B, for the Stratigraphy and Paleontology group at Earth Sciences, UU.

See [[file:full_literal_workflow.org]] for the entire workflow! This is a [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]] example, where the code itself is surrounded by rich-text explanation.
If we need to run the workflow, we can [[https://orgmode.org/manual/Extracting-Source-Code.html#Extracting-Source-Code][~tangle~ the files]] to generate the ~_targets.R~ file as well as the ~R/functions.R~ file.

The required R packages for this workflow are:

- [[https://github.com/isoverse/clumpedr/][~clumpedr~ package]], install with ~devtools::install_github("isoverse/clumpedr")~ to do the generic clumped isotope calculations
- tidyverse packages :: It's probably easiest to just install them all...
  - dplyr :: data wrangling
  - readr :: reading/writing csv files
  - purrr :: functional programming, never loop again
  - tibble :: better data.frames
  - ... ?
- readxl :: to read in our excel files with metadata changes
- qs :: for optimized cache of lists
- fst :: for optimized cache of data.frames and tibbles
- isoreader :: to read in the raw files
- slider :: for the rolling empirical transfer function (currently not preferred)
- targets :: for the cached reproducible pipeline workflow
- tidylog :: for neat log messages about dplyr verbs